# Generated by Django 5.2 on 2025-04-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_roomnotification'),
        ('base', '0010_roomnotification_type'),
    ]

    operations = [
    ]
