# Generated by Django 5.2 on 2025-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_merge_20250422_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnotification',
            name='type',
            field=models.CharField(choices=[('joined', 'Joined'), ('rejected', 'Rejected'), ('removed', 'Removed')], max_length=10),
        ),
    ]
